#!/bin/bash
echo Starting master on $SPARK_MASTER
mkdir -p $SPARK_LOG_DIR $SPARK_WORKER_DIR
start-master.sh
# sleep a tiny little bit to allow master to start

echo Starting slaves
#(old) srun spark-class org.apache.spark.deploy.worker.Worker $SPARK_MASTER -d $SPARK_WORKER_DIR &
#srun -n600 --reservation=COFFEA --partition=hammer-a -A cms spark-class org.apache.spark.deploy.worker.Worker $SPARK_MASTER -d $SPARK_WORKER_DIR
srun -N16 -n128  --reservation=COFFEA -A cms spark-class org.apache.spark.deploy.worker.Worker $SPARK_MASTER -d $SPARK_WORKER_DIR
